language: php

php:
  - 5.3

before_script:
  - printf "\n" | pecl install imagick
  - ./tests/before_script.sh


script: phpunit --verbose -c tests/phpunit.xml

notifications:
  email:
    - maxtobiasweber@gmail.com