language: php
php:
  - 5.3

env:
  global:
    - secure: nK5WFJHTg8NLlK7gqDPlbqjiNWLQNhVKxiZpsahL9YXzF0YPnTvt14Fy63AVqPdxHkP6KRTRtRFHZYylw1EKFmLFsyhcQ99W/PHLQ/JyTCNWIIGUA9yw11Xmyj5acqGv8Oc1AM3bZ5R3YHQ9CioQcLFcGYmAu/Ti+oHTsFdkVsY=
    - secure: OfCzzcQANLBaryAJnbdc9GBMsjGsEe2B5oKbhJOb8535jhgXPtgPXuPSFZgkaxwFp4zcZez3OFPMgJXA8KTiliGZd6YGBm+Td8ZqK7hlXG1keH3NljZhfRirduawNWSsXQX3qEqReEfsquZjy6n1W3GDhDPnkqkAp6HBHUEGFjQ=
    
before_script:
  # - printf "\n" | pecl install imagick
  # - ./tests/before_script.sh
  - ./tests/saucelab_test.sh

script: phpunit --verbose -c tests/phpunit.xml
notifications:
  email:
    - maxtobiasweber@gmail.com